<?php
// File: /cms/helpers/TemplateGenerator.php

require_once __DIR__ . '/../PageContent.php';

class TemplateGenerator
{
    public static function regenerate()
    {
        $pageContent = new PageContent();
        $entries = $pageContent->getAll();

        $output = "<?php\n\n";
        $output .= "// Auto-generated by CMS\n\n";

        foreach ($entries as $entry) {
            $page = htmlspecialchars($entry['page_name']);
            $section = htmlspecialchars($entry['section_name']);
            $title = htmlspecialchars($entry['title']);
            $subtitle = htmlspecialchars($entry['subtitle']);
            $description = htmlspecialchars($entry['description']);
            $extra_description = htmlspecialchars($entry['extra_description']);
            $image_path = htmlspecialchars($entry['image_path']);
            $icon_class = htmlspecialchars($entry['icon_class']);
            $officer_name = htmlspecialchars($entry['officer_name']);
            $officer_position = htmlspecialchars($entry['officer_position']);
            $contact_phone = htmlspecialchars($entry['contact_phone']);
            $contact_email = htmlspecialchars($entry['contact_email']);
            $contact_location = htmlspecialchars($entry['contact_location']);
            $facebook_link = htmlspecialchars($entry['facebook_link']);

            $output .= "// Page: $page | Section: $section\n";
            $output .= "?>\n";
            $output .= "<section id=\"$section\">\n";

            if ($title) $output .= "  <h2>$title</h2>\n";
            if ($subtitle) $output .= "  <h3>$subtitle</h3>\n";
            if ($image_path) $output .= "  <img src=\"$image_path\" alt=\"$title\">\n";
            if ($icon_class) $output .= "  <i class=\"$icon_class\"></i>\n";
            if ($description) $output .= "  <p>$description</p>\n";
            if ($extra_description) $output .= "  <p>$extra_description</p>\n";

            // Officers section
            if ($officer_name || $officer_position) {
                $output .= "  <div class=\"officer\">\n";
                if ($officer_name) $output .= "    <strong>Name:</strong> $officer_name<br>\n";
                if ($officer_position) $output .= "    <strong>Position:</strong> $officer_position\n";
                $output .= "  </div>\n";
            }

            // Contact section
            if ($contact_phone || $contact_email || $contact_location || $facebook_link) {
                $output .= "  <div class=\"contact-info\">\n";
                if ($contact_phone) $output .= "    <p>Phone: $contact_phone</p>\n";
                if ($contact_email) $output .= "    <p>Email: $contact_email</p>\n";
                if ($contact_location) $output .= "    <p>Location: $contact_location</p>\n";
                if ($facebook_link) $output .= "    <p><a href=\"$facebook_link\">Facebook</a></p>\n";
                $output .= "  </div>\n";
            }

            $output .= "</section>\n\n<?php\n\n";
        }

        // Write to template_views.php
        file_put_contents(__DIR__ . '/../template_views.php', $output);
    }
}
?>
