-- Fix Mission table
ALTER TABLE af_page_mission
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST;

-- Fix Vision table
ALTER TABLE af_page_vision
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST;

-- Fix MV table
ALTER TABLE af_page_mv
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST; 